### ISSUE TITLE
How do I set the code up for me to modify it

### ISSUE THREAD

**Issue by Urganot** [hytonhan/Timberborn-SimpleFloodgateTriggers#17]
Hi,

I'd like to contribute to the development. The issue is that I cant get rider to find all the dependencies. Even if I add the dlls manually, it cant access stuff like "DayNightCycle" because its flagged as internal

**Comment by hytonhan** [comment]
Hello,

Unfortunately I don't know how to set up Rider. I've only used Visual Studio. TimberApi should have a dependency to Timberborn.gamelibs, which has the gamefiles as publizised. Might require you to add BaGet as a package source (https://nuget.bepinex.dev/v3/index.json)

**Comment by Urganot** [comment]
Oh, I forgot to add the package source :)
thanks for your help
