### ISSUE TITLE
Update 6

### ISSUE THREAD

**Issue by babs** [hytonhan/Timberborn-SimpleFloodgateTriggers#26]
Hello,

First of all thanks for this amazing mod that made life waaayyyy easier;)

Do you plan to make it compatible with update 6 ?

**Comment by hytonhan** [comment]
Hello,

Unfortunately probably not. I don't play Timberborn anymore and my time is very limited, so currently I don't see myself updating this to U6.

**Comment by babs** [comment]
Thanks for the news, I wish you well then ;)
