### ISSUE TITLE
Crash in most recent experimental version

### ISSUE THREAD

**Issue by vidiot5533** [hytonhan/Timberborn-SimpleFloodgateTriggers#5]
Mods used:
BepInExPack, TimberAPI, Simple Floodgate Triggers, Tiny Warehouse, More Platforms, Ladder

Recreation of the bug:
Playing without setting any triggers will not yield a crash. Setting a floodgate to trigger based on water level marker causes my game to crash within a few in-game days. Not entirely sure, but it also only crashed during a drought, this may be due to when I set the trigger or part of the bug.

Additional Information:
Possibly related, the floodgate I tried to set up does not affect adjacent floodgates regardless of whether sync was turned on. I tried turning sync off to see if it would no longer crash, this did not help. Also, I did not try any other trigger settings, as this is the one trigger I desire, although the bug may also be present with other trigger options

**Comment by hytonhan** [comment]
Hey! This is a known issue on experimental. There are breaking changes between stable and experimental on the gamesave system, which causes FloodgateMod to crash when the game saves if there are existing link between floodgates and streamgauges. I will fix this when experimental hits stable. Unfortunately that also means that in experimental only the drought/schedule settings will work. Sorry for the inconvinience!

**Comment by vidiot5533** [comment]
I realized after looking through the closed issues that this was a known issue, I think it would be best to leave it open so that others like myself don't think this is a new issue.

**Comment by hytonhan** [comment]
Good call, leaving open until current experimental hits stable

**Comment by R-T-B** [comment]
https://github.com/R-T-B/Timberborn-SimpleFloodgateTriggers/releases/tag/1.0.3

For those who want, working build for experimental.  No plans to takeover or anything, this is an interim thing just until next stable.

Source is at same repo.
