### ISSUE TITLE
New bug

### ISSUE THREAD

**Issue by rodopoulos1** [hytonhan/Timberborn-SimpleFloodgateTriggers#8]
[Error  : Unity Log] NullReferenceException: Object reference not set to an instance of an object
Stack trace:
Hytone.Timberborn.Plugins.Floodgates.EntityAction.StreamGaugeMonoBehaviour.Tick () (at <cc400e0aa51d44c093ef69b62b2e0634>:0)
Timberborn.TickSystem.TickableComponent.StartAndTick () (at <981eb0b1e6b84602b601b80a36ef1ae8>:0)
Frog.PerfFixPlugin.TickableEntityTickTickableComponents (Timberborn.TickSystem.TickableEntity __instance) (at <f542830770b04beb91fb262a3a2d50db>:0)
(wrapper dynamic-method) Timberborn.TickSystem.TickableEntity.DMD<Timberborn.TickSystem.TickableEntity::TickTickableComponents>(Timberborn.TickSystem.TickableEntity)
Frog.PerfFixPlugin.TickableEntityTick (Timberborn.TickSystem.TickableEntity __instance) (at <f542830770b04beb91fb262a3a2d50db>:0)
Rethrow as Exception: Exception thrown while ticking entity 22a19e41-13b3-4cf5-ac7e-63ad27443712 'StreamGauge.Folktails(Clone)'
Frog.PerfFixPlugin.TickableEntityTick (Timberborn.TickSystem.TickableEntity __instance) (at <f542830770b04beb91fb262a3a2d50db>:0)
(wrapper dynamic-method) Timberborn.TickSystem.TickableEntity.DMD<Timberborn.TickSystem.TickableEntity::Tick>(Timberborn.TickSystem.TickableEntity)
Timberborn.TickSystem.TickableEntityBucket.TickAll () (at <981eb0b1e6b84602b601b80a36ef1ae8>:0)
Timberborn.TickSystem.TickableBucketService.TickNextBucket () (at <981eb0b1e6b84602b601b80a36ef1ae8>:0)
Timberborn.TickSystem.TickableBucketService.TickBuckets (System.Int32 numberOfBucketsToTick) (at <981eb0b1e6b84602b601b80a36ef1ae8>:0)
Timberborn.TickSystem.Ticker.Update (System.Single deltaTimeInSeconds) (at <981eb0b1e6b84602b601b80a36ef1ae8>:0)
Timberborn.TickSystem.TickerUpdater.Update () (at <981eb0b1e6b84602b601b80a36ef1ae8>:0)

[Error  : Unity Log] NullReferenceException: Object reference not set to an instance of an object
Stack trace:
Hytone.Timberborn.Plugins.Floodgates.EntityAction.StreamGaugeMonoBehaviour.Tick () (at <cc400e0aa51d44c093ef69b62b2e0634>:0)
Timberborn.TickSystem.TickableComponent.StartAndTick () (at <981eb0b1e6b84602b601b80a36ef1ae8>:0)
Frog.PerfFixPlugin.TickableEntityTickTickableComponents (Timberborn.TickSystem.TickableEntity __instance) (at <f542830770b04beb91fb262a3a2d50db>:0)
(wrapper dynamic-method) Timberborn.TickSystem.TickableEntity.DMD<Timberborn.TickSystem.TickableEntity::TickTickableComponents>(Timberborn.TickSystem.TickableEntity)
Frog.PerfFixPlugin.TickableEntityTick (Timberborn.TickSystem.TickableEntity __instance) (at <f542830770b04beb91fb262a3a2d50db>:0)
Rethrow as Exception: Exception thrown while ticking entity 22a19e41-13b3-4cf5-ac7e-63ad27443712 'StreamGauge.Folktails(Clone)'
Frog.PerfFixPlugin.TickableEntityTick (Timberborn.TickSystem.TickableEntity __instance) (at <f542830770b04beb91fb262a3a2d50db>:0)
(wrapper dynamic-method) Timberborn.TickSystem.TickableEntity.DMD<Timberborn.TickSystem.TickableEntity::Tick>(Timberborn.TickSystem.TickableEntity)
Timberborn.TickSystem.TickableEntityBucket.TickAll () (at <981eb0b1e6b84602b601b80a36ef1ae8>:0)
Timberborn.TickSystem.TickableBucketService.TickNextBucket () (at <981eb0b1e6b84602b601b80a36ef1ae8>:0)
Timberborn.TickSystem.TickableBucketService.TickBuckets (System.Int32 numberOfBucketsToTick) (at <981eb0b1e6b84602b601b80a36ef1ae8>:0)
Timberborn.TickSystem.Ticker.Update (System.Single deltaTimeInSeconds) (at <981eb0b1e6b84602b601b80a36ef1ae8>:0)
Timberborn.TickSystem.TickerUpdater.Update () (at <981eb0b1e6b84602b601b80a36ef1ae8>:0)

[Error  : Unity Log] NullReferenceException: Object reference not set to an instance of an object
Stack trace:
Timberborn.CoreUI.PanelStack.Awake () (at <77498430b31649a1b27343508f9e2bc3>:0)

**Comment by hytonhan** [comment]
Hello. Could you describe what you were doing or what you had done, so I can investigate this better? Thanks for reporting

**Comment by hytonhan** [comment]
I have found the the issue. The PerformanceFix mod is not compatible with SimpleFloodgateTriggers, which causes the crash. Maybe this will be fixed in the future. In the meantime I suggest to disable either SimpleFloodgateTriggers or PerformanceFix.
